services:
  prometheus:
    image: prom/prometheus:latest
    container_name: lab055-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app1
      - app2
      - node-exporter
    stdin_open: true
    tty: true

  app1:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: lab055-app1
    ports:
      - "8081:8080"

  app2:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: lab055-app2
    ports:
      - "8082:8080"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: lab055-node-exporter
    ports:
      - "9100:9100"
