apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    type: database
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-storage
  hostPath:
    path: /data/db
